# Generated by Django 3.2.7 on 2021-11-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phoneNumber', models.CharField(max_length=11)),
                ('referralCode', models.CharField(default='Optional', max_length=8)),
            ],
        ),
    ]
