# Generated by Django 3.2.7 on 2021-11-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogExAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='fullname',
            field=models.CharField(default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='phoneNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='business',
            name='referralCode',
            field=models.CharField(default='new', max_length=8),
        ),
        migrations.AlterField(
            model_name='business',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
