# Generated by Django 3.2.7 on 2021-11-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogExAPP', '0002_auto_20211104_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='business',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='referralCode',
            field=models.CharField(default='Optional', max_length=8),
        ),
        migrations.AlterField(
            model_name='business',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
