# Generated by Django 3.2.7 on 2021-11-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogExAPP', '0003_auto_20211104_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phoneNumber',
            field=models.IntegerField(max_length=11),
        ),
    ]
