# Generated by Django 3.2.7 on 2021-11-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogExAPP', '0005_auto_20211107_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='referral_Code',
            new_name='referral_code',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phonen_number',
        ),
        migrations.AddField(
            model_name='business',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
